// loại đồng hồ (type select)
const typeClocks = [
  { value: "actarisd15", label: "Actaris D15" },
  { value: "actarisd20", label: "Actaris D20" },
  { value: "actarisd25", label: "Actaris D25" },
  { value: "actarisd32", label: "Actaris D32" },
  { value: "actarisd40", label: "Actaris D40" },
  { value: "actarisd50", label: "Actaris D50" },
  { value: "aichid15", label: "Aichi D15" },
  { value: "ashid15", label: "Ashi D15" },
  { value: "ashi20", label: "Ashi D20" },
  { value: "ashi25", label: "Ashi D25" },
  { value: "ashi40", label: "Ashi D40" },
  { value: "ashi50", label: "Ashi D50" },
  { value: "ashi80", label: "Ashi D80" },
  { value: "itrond15", label: "Itron D15" },
  { value: "itrond20", label: "Itron D20" },
  { value: "itrond25", label: "Itron D25" },
  { value: "itrond32", label: "Itron D32" },
  { value: "itrond40", label: "Itron D40" },
  { value: "itrond50", label: "Itron D50" },
  { value: "ketd15", label: "Ket D15" },
  { value: "kividod15", label: "Kivido D15" },
  { value: "metcon15", label: "Metcon D15" },
  { value: "metcon20", label: "Metcon D20" },
  { value: "metcon25", label: "Metcon D25" },
  { value: "metcon32", label: "Metcon D32" },
  { value: "metcon40", label: "Metcon D40" },
  { value: "metcon50", label: "Metcon D50" },
  { value: "minold15", label: "Minol D15" },
  { value: "minold20", label: "Minol D20" },
  { value: "phapd15", label: "Phap D15" },
  { value: "phapd20", label: "Phap D20" },
  { value: "phapd25", label: "Phap D25" },
  { value: "phapd40", label: "Phap D40" },
  { value: "phapd50", label: "Phap D50" },
  { value: "phuthinh", label: "Phuthinh" },
  { value: "sumergerd15", label: "Sumerger D15" },
  { value: "sumergerd20", label: "Sumerger D20" },
  { value: "sumergerd25", label: "Sumerger D25" },
  { value: "thaiaichi", label: "Thai Aichi" },
  { value: "thaivuongd15", label: "Thai Vuong D15" },
  { value: "khac", label: "Khác" },
];

export { typeClocks };
